### ISSUE TITLE
Missing interface Phlickr_Framework_IObjectBase

### ISSUE THREAD

**Issue by ylazarov** [alchemy-fr/Phlickr#2]
Attempted to load interface "Phlickr_Framework_IObjectBase" from the global namespace in ...

**Comment by schlozik** [comment]
Solution ?  Interface IObjectBase is not exist  :(

**Comment by mattchatterley** [comment]
I got around this by just removing the requirement for IObjectBase, as follows:

```
//require_once 'Phlickr/Framework/IObjectBase.php';

abstract class Phlickr_Framework_ObjectBase {//implements Phlickr_Framework_IObjectBase {
```

Will submit a pull request (although repo seems to be a bit dead?) if I get a chance.

**Comment by fabre-thibaud** [comment]
Proper solution would be to run composer install :)
